def fail():
    raise Exception('fail')
